Numpy bir kütüphanedir. İçerisinde farklı methodlar barındırır.

Bu kütüphane import edilerek içerisindeki methodlar kullanılır.

İstatiksel işlemler yapmak için kullanılır.


In [1]:
import numpy as np #numpy kütüphanesi import edildi

In [3]:
array = np.array([1,2,3])  #numpy kütüphanesi çağırılarak array oluşturuldu.
print(array)

[1 2 3]


In [4]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(array2.shape) #arrayin shapine bakılır.
#(15 , )15-1'lik vektör demektir.

(15,)


In [5]:
a = array2.reshape(3,5) #array2 3'e 5'lik bir matrise dönüştürüldü.
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [7]:
print("Shape:",a.shape) #oluşturulan matrisin shape'ine bakmak için.
print("Dimension: ",a.ndim) #boyuta bakmak için.
print("data type: ",a.dtype.name) #tipine bakmak için.Genellikle int32'dir.
print("Size: ",a.size)#reshape'den önceki boyutu verir.
print("type: ",type(a)) 

Shape: (3, 5)
Dimension:  2
data type:  int32
Size:  15
type:  <class 'numpy.ndarray'>


In [9]:
array3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #reshape komutu kullanılmadan da boyut değiştirilebilir.
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(array3.shape) #3 satır 4 sütun (3,4) 

(3, 4)


In [11]:
zeros= np.zeros((3,4)) #3 satır 4 sütunluk sıfırlardan oluşan array oluşturulur.
#bu matris ile memoryde yer ayırtılır, güncelleme yapılmak istendiğinde güncellenir.
#append gibi fonksiyonlar memory'iyi yorar ve programı yavaşlatır.
#o yüzden bu method tercih edilir.

In [12]:
zeros[0,0]=5
print(zeros) #0.satır 0.sütun 5 değeri verildi.

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
np.ones((3,4)) #1'lerden oluşan 3*4'lük bir matris oluşturulur.


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.empty((4,5)) #4*5'lik boş bir matris oluşturulur.

array([[2.92864070e-312, 0.00000000e+000, 1.41537862e+161,
        5.22182633e+180, 7.33952596e+223],
       [4.83245960e+276, 4.57667791e-072, 4.57667790e-072,
        6.01391519e-154, 7.06764512e-096],
       [7.06743455e-096, 1.81148490e-152, 6.14099335e-071,
        4.57667790e-072, 1.95360427e-109],
       [2.86752281e+161, 2.78225500e+296, 9.80058441e+252,
        1.23971686e+224, 6.80146171e-310]])

In [16]:
np.arange(10,50,5) #10 ve 50 arasındaki sayılar 5'er 5'er yazdırılır.
#array([10, 15, 20, 25, 30, 35, 40, 45])

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
a= np.linspace(0,10,20) #0 ile 10 arasında 20 tane sayı yazdırılır.
print(a)

Numpy Basic Operations

In [19]:
a = np.array([1,2,3])
b = np.array([4,5,6]) #toplama çıkarma gibi işlemlerde matrislerin boyutlarının aynı olması gerekir.
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [20]:
#arraylerde saymaya sıfırdan başlanır.
a= np.array([1,2,3,4,5,6,7]) #vektor -> dimension 1

In [22]:
#array-liste farkı
liste = [1,2,3,4]

array = np.array([5,6,7,8])
#array tanımlamak için array'in içine liste yazılır.
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [23]:
array = np.array(liste) #listeden array'e geçiş.
print(array)

[1 2 3 4]


In [24]:
liste2 = list(array)
print(liste2) #arrayden listeye geçiş

[1, 2, 3, 4]


In [25]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [26]:
b=a

c=a

b[0]=5 #bu örnekte a,b,c arraylerinin hepsinin 0. indeksi değişir.
#bunun sebebi np.array memory'de bir değer olarak değil bir alan olarak depolanır.
#a,b,c için memory aynı alan ayrıldığından bir tanesi değiştirilince hepsi değişir.
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [29]:
d = a.copy() #copy methoduyla memory yeni bir alan tahsis edilir.
#böylelikle birinin bir indeksi değişince diğerleri bundan etkilenmez.
#[1 2 3]

In [31]:
a= np.array([1,2,3,4,5,6,7]) #vector -> dimension 1
print(a)

[1 2 3 4 5 6 7]


In [32]:
print(a[0])

1


In [33]:
print(a[0:4]) #0.indexten 4.indexe kadar olan sayıları verir.4.index dahil değil.

[1 2 3 4]


In [34]:
reverseArray = a[::-1] #array'i ters çevirir

In [35]:
print(reverseArray)

[7 6 5 4 3 2 1]


In [36]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
print(b[0,0]) #1'i verir.
print(b[1,1]) #7'yi verir.
print(b[1:2]) #1.satır 2.sütun
print(b[1:])  #2.sütunun tüm elemanlarını
print(b[1,1:4]) #2.satır 2. 3. 4. sütunları verir 


1
7
[[ 6  7  8  9 10]]
[[ 6  7  8  9 10]]
[7 8 9]


In [39]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]]) #3*3'lük array oluşturuldu.
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
a = array.ravel() #ravel methoduyla tek boyutlu hale getirilir.
print(a)

[1 2 3 4 5 6 7 8 9]


In [41]:
array2 = a.reshape(3,3) #tekrardan 3*3'lük array haline getirildi.
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
array_transpose = array2.T #array'in transpose'u alınır.
                        
print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [43]:
array3 = np.array([[1,2],[3,4],[5,6]])
print(array3)

[[1 2]
 [3 4]
 [5 6]]


In [44]:
array3.resize((2,3)) #resize ile yapılan boyut değişimleri kalıcıdır, aynı array'in içine kaydeder.
#reshape ile yapılan değişimler kalıcı değildir. yapılan değişim başka bir değişkene kaydedilmelidir.
print(array3)

[[1 2 3]
 [4 5 6]]
